
spring:
  application:
    name: 'Subscription RabbitMQ'
  r2dbc:
    url: r2dbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSRGRES_DATABASE:subscription}
    username: ${POSTGRES_USERNAME:subscription.svc}
    password: ${POSTGRES_PASSWORD:subscription.svc}
  rabbitmq:
    host: ${RABBIT_MQ_HOST:localhost}
    username: ${RABBIT_MQ_USERNAME:subscription.svc}
    password: ${RABBIT_MQ_PASSWORD:subscription.svc}
    port: ${RABBIT_MQ_PORT:5672}
    exchange: ${RABBIT_MQ_EXCHANGE:subscription}
    routing-key: ${RABBIT_MQ_ROUTING_KEY:subscription}
    queue: ${RABBIT_MQ_QUEUE:subscription}

springdoc:
  api-docs.path: /api-documentation
  swagger-ui:
    path: /docs

logging:
  level:
    org:
      springframework:
        data:
          r2dbc: DEBUG